# Generated by Django 2.2.7 on 2020-02-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_googlemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='menu1',
            field=models.ImageField(default='default.jpg', upload_to='menu_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='menu2',
            field=models.ImageField(default='default.jpg', upload_to='menu_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='menu3',
            field=models.ImageField(default='default.jpg', upload_to='menu_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='menu4',
            field=models.ImageField(default='default.jpg', upload_to='menu_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='googlemap',
            field=models.CharField(default='https://www.google.co.th/maps/', max_length=999999),
        ),
    ]
