# Generated by Django 2.2.7 on 2020-02-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='googlemap',
            field=models.CharField(default='default.jpg', max_length=999999),
        ),
    ]
