# Generated by Django 2.2.7 on 2020-02-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200220_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='googlemap',
            field=models.CharField(default='default.jpg', max_length=500),
        ),
    ]
