# Generated by Django 2.2.7 on 2020-02-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200220_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='RestuarantName',
        ),
    ]
