# Generated by Django 2.2.7 on 2020-02-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='foodpanda',
            field=models.CharField(choices=[('มี', 'มี'), ('ไม่มี', 'ไม่มี')], default='มี', max_length=6),
        ),
        migrations.AddField(
            model_name='post',
            name='grab',
            field=models.CharField(choices=[('มี', 'มี'), ('ไม่มี', 'ไม่มี')], default='มี', max_length=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='googlemap',
            field=models.CharField(default='https://www.google.com/maps/embed?pb=!1m18......', max_length=500),
        ),
    ]
