# Generated by Django 2.2.7 on 2020-02-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200223_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='closeday',
            field=models.CharField(choices=[('จันทร์', 'จันทร์'), ('อังคาร', 'อังคาร'), ('พุธ', 'พุธ'), ('พฤหัส', 'พฤหัส'), ('ศุกร์', 'ศุกร์'), ('เสาร์', 'เสาร์'), ('อาทิตย์', 'อาทิตย์')], default='อาทิตย์', max_length=6),
        ),
        migrations.AddField(
            model_name='post',
            name='openday',
            field=models.CharField(choices=[('จันทร์', 'จันทร์'), ('อังคาร', 'อังคาร'), ('พุธ', 'พุธ'), ('พฤหัส', 'พฤหัส'), ('ศุกร์', 'ศุกร์'), ('เสาร์', 'เสาร์'), ('อาทิตย์', 'อาทิตย์')], default='จันทร์', max_length=6),
        ),
    ]
