# Generated by Django 3.0.3 on 2020-04-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200223_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closeday', models.CharField(choices=[('อาหารใต้', 'อาหารใต้'), ('อาหารเหนือ', 'อาหารเหนือ'), ('อาหารอีสาน', 'อาหารอีสาน')], default='อาหารทั่วไป', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='closeday',
            field=models.CharField(choices=[('จันทร์', 'จันทร์'), ('อังคาร', 'อังคาร'), ('พุธ', 'พุธ'), ('พฤหัส', 'พฤหัส'), ('ศุกร์', 'ศุกร์'), ('เสาร์', 'เสาร์'), ('อาทิตย์', 'อาทิตย์')], default='อาทิตย์', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='openday',
            field=models.CharField(choices=[('จันทร์', 'จันทร์'), ('อังคาร', 'อังคาร'), ('พุธ', 'พุธ'), ('พฤหัส', 'พฤหัส'), ('ศุกร์', 'ศุกร์'), ('เสาร์', 'เสาร์'), ('อาทิตย์', 'อาทิตย์')], default='จันทร์', max_length=10),
        ),
    ]
