# Generated by Django 3.0.3 on 2020-04-08 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_tag_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagged',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Posts', to='blog.Tag'),
        ),
    ]
