# Generated by Django 3.0.3 on 2020-04-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_post_tagged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tagged',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
