# Generated by Django 3.0.3 on 2020-04-08 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='post',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='blog.Post'),
            preserve_default='True',
        ),
    ]
