# Generated by Django 3.0.3 on 2020-04-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_tag_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
