# Generated by Django 3.0.3 on 2020-04-15 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0026_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('pic1', models.ImageField(default='default.jpg', upload_to='menu_pics')),
                ('pic2', models.ImageField(default='default.jpg', upload_to='menu_pics')),
                ('pic3', models.ImageField(default='default.jpg', upload_to='menu_pics')),
                ('pic4', models.ImageField(default='default.jpg', upload_to='menu_pics')),
                ('content', models.TextField()),
                ('address', models.CharField(default='', max_length=50)),
                ('googlemap', models.CharField(default='https://www.google.com/maps/embed?pb=!1m18......', max_length=500)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
