# Generated by Django 3.0.3 on 2020-04-26 13:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_reviewcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='foodtype',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('อาหารไทย', 'อาหารไทย'), ('อาหารญี่ปุ่น', 'อาหารญี่ปุ่น'), ('อาหารอีสาน', 'อาหารอีสาน')], default='อาหารไทย', max_length=32),
        ),
    ]
