# Generated by Django 3.0.3 on 2020-04-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_post_foodtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='foodtype',
        ),
    ]
