# Generated by Django 3.0.3 on 2020-04-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_remove_post_foodtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_chinesefood',
            field=models.BooleanField(default=False, verbose_name='IS chinesefood'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_japanfood',
            field=models.BooleanField(default=False, verbose_name='IS japanfood'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_thaifood',
            field=models.BooleanField(default=False, verbose_name='IS thaifood'),
        ),
    ]
