# Generated by Django 3.0.3 on 2020-04-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20200426_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_buffetfood',
            field=models.BooleanField(default=False, verbose_name='บุฟเฟ่ต์'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_cafefood',
            field=models.BooleanField(default=False, verbose_name='กาแฟ&ของหวาน'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_fastfood',
            field=models.BooleanField(default=False, verbose_name='ฟาสต์ฟู้ด'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_noodlefood',
            field=models.BooleanField(default=False, verbose_name='ก๋วยเตี๋ยว'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_northfood',
            field=models.BooleanField(default=False, verbose_name='อาหารใต้'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_somtumfood',
            field=models.BooleanField(default=False, verbose_name='ส้มตำ'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_southfood',
            field=models.BooleanField(default=False, verbose_name='อาหารใต้'),
        ),
    ]
