# Generated by Django 3.0.3 on 2020-04-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20200426_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_northfood',
            field=models.BooleanField(default=False, verbose_name='อาหารเหนือ'),
        ),
    ]
